sonar.projectKey=sw5005-sus_ceramicraft-customer-support-agent
sonar.organization=sw5005-sus
sonar.projectName=ceramicraft-customer-support-agent

sonar.sources=src/ceramicraft_customer_support_agent
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
