# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cs_agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cs_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63s_agent.proto\x12\x14\x63\x65ramicraft.cs_agent\"1\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\"0\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\"!\n\x0cResetRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\"0\n\rResetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb7\x01\n\x14\x43ustomerSupportAgent\x12M\n\x04\x43hat\x12!.ceramicraft.cs_agent.ChatRequest\x1a\".ceramicraft.cs_agent.ChatResponse\x12P\n\x05Reset\x12\".ceramicraft.cs_agent.ResetRequest\x1a#.ceramicraft.cs_agent.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cs_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=40
  _globals['_CHATREQUEST']._serialized_end=89
  _globals['_CHATRESPONSE']._serialized_start=91
  _globals['_CHATRESPONSE']._serialized_end=139
  _globals['_RESETREQUEST']._serialized_start=141
  _globals['_RESETREQUEST']._serialized_end=174
  _globals['_RESETRESPONSE']._serialized_start=176
  _globals['_RESETRESPONSE']._serialized_end=224
  _globals['_CUSTOMERSUPPORTAGENT']._serialized_start=227
  _globals['_CUSTOMERSUPPORTAGENT']._serialized_end=410
# @@protoc_insertion_point(module_scope)
